project:
  type: website

website:
  title: "Asset Map"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: sections/asset_map_dashboards.qmd
        text: Asset Map Dashboards
      - href: sections/demographics.qmd
        text: Demographics
      - href: sections/resources.qmd
        text: Resources

format:
  html:
    page-layout: full
    theme: 
    - sandstone
    - assets/custom_style.css # custom formatting for value boxes
    css: assets/custom_styles.css # custom formatting for value boxes
    toc: false
execute:
  freeze: auto


