project:
  type: website

website:
  title: "asset_map_website"
  navbar:
    left:
      - href: sections/index.qmd
        text: Home
      - sections/about.qmd
      - sections/asset_map_overview_visual.qmd

format:
  html:
    page-layout: full
    theme: 
    - cosmo
    - assets/custom_styles.css # custom formatting for value boxes
    css: styles.css
    toc: false



