project:
  type: website

website:
  title: "Travis County Justice Department Asset Map Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: sections/asset_map_overview_visual.qmd
        text: Asset Map Dashboard
      - href: sections/resources.qmd
        text: Resources

format:
  html:
    page-layout: full
    theme: 
    - sandstone
    - assets/custom_style.css # custom formatting for value boxes
    css: assets/custom_styles.css # custom formatting for value boxes
    toc: false
execute:
  freeze: auto


